cart/urls.py
# In carts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('update/<int:item_id>/', views.update_cart, name='update_cart'),
    path('remove/<int:item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('detail/', views.cart_detail, name='cart_detail'),
]

kebanda/urls.py
from django.contrib import admin
from django.urls import path, include
from django.http import HttpResponse
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('storefront.urls')),
    path('products/', include('products.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('payments/', include('payments.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('checkout/', views.checkout, name='checkout'),
    path('summary/<int:order_id>/', views.order_summary, name='order_summary'),
    path('complete/<int:order_id>/', views.complete_order, name='complete_order'),
    path('orders/', views.user_orders, name='orders'),

]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}My E-commerce Site{% endblock %}</title>
    <style>
        body {
            background-color: brown;
            text-align: center;
            color: white;
        }

        div{
            border: solid white 1px;
        }

        nav{
            color: yellowgreen;
        }
        a{
            color: rgb(170, 255, 0);
        }
        h1{
            color: yellow;
        }
        h2{
            color: oldlace;
        }
        form{
            text-align: left;
            margin-left: 30%;
        }
        nav{
            background-color: black;
            padding: 10px;
        }

    </style>

</head>
<body>
    <header>
        <h1>KeBanda E-commerce Site</h1>
        <nav>
            <a href="{% url 'home' %}">Home</a>
            <a href="{% url 'product_list' %}">Products</a>
			<a href="{% url 'cart_detail' %}">cart</a>


            {% if user.is_authenticated %}
            <a href="{% url 'logout' %}">LogOut</a>
            <a href="{% url 'profile' %}">Profile</a>
            <a href="{% url 'orders:orders' %}">My orders</a>
                {% if user.is_superuser %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'admin:index' %}" target="_blank">Admin</a>
                    </li>
                {% endif %}
            {% else %}
			
			<a href="{% url 'login' %}">LogIn</a>
            <a href="{% url 'register' %}">Register</a>
            {% endif %}

        </nav>
    </header>
    {% if messages %}
    <div class="messages">
        {% for message in messages %}
            <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">
                {{ message }}
            </div>
        {% endfor %}
    </div>
    {% endif %}

    <main>
        {% block content %}{% endblock %}
    </main>

    <footer>
        <p>&copy; 2024 My E-commerce Site</p>
    </footer>
</body>
</html>